const GET_INITIAL_DATA = 'GET-INITIAL-DATA';
const UPDATE_ROW = "UPDATE-ROW";
const UPDATE_SIDEBAR = "UPDATE-SIDEBAR";
const UPDATE_FOOTER = "UPDATE-FOOTER";

export {
    GET_INITIAL_DATA,
    UPDATE_ROW,
    UPDATE_SIDEBAR,
    UPDATE_FOOTER
}