const GET_INITIAL_DATA = 'GET-INITIAL-DATA';
const ADD_NEW_ROW = 'ADD-NEW-ROW';
const UPDATE_ROW = "UPDATE-ROW";
const DELETE_ROW = "DELETE-ROW";
const UPDATE_SIDEBAR = "UPDATE-SIDEBAR";
const UPDATE_FOOTER = "UPDATE-FOOTER";

export {
    GET_INITIAL_DATA,
    ADD_NEW_ROW,
    UPDATE_ROW,
    DELETE_ROW,
    UPDATE_SIDEBAR,
    UPDATE_FOOTER
}